language: cpp
sudo: false

matrix:
  include:
  - os: linux
    arch: amd64
    dist: bionic
    compiler: gcc

  - os: linux
    arch: amd64
    dist: bionic
    compiler: clang

  - os: linux
    arch: arm64
    dist: bionic
    compiler: gcc

before_script:
  - mkdir build && cd build
  - cmake ..

script:
  - make
